// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ServerInfo.proto

#ifndef PROTOBUF_ServerInfo_2eproto__INCLUDED
#define PROTOBUF_ServerInfo_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace ServerInfo {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_ServerInfo_2eproto();
void protobuf_AssignDesc_ServerInfo_2eproto();
void protobuf_ShutdownFile_ServerInfo_2eproto();

class Packet;

// ===================================================================

class Packet : public ::google::protobuf::Message {
 public:
  Packet();
  virtual ~Packet();

  Packet(const Packet& from);

  inline Packet& operator=(const Packet& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Packet& default_instance();

  void Swap(Packet* other);

  // implements Message ----------------------------------------------

  Packet* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Packet& from);
  void MergeFrom(const Packet& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 types = 1;
  inline bool has_types() const;
  inline void clear_types();
  static const int kTypesFieldNumber = 1;
  inline ::google::protobuf::int32 types() const;
  inline void set_types(::google::protobuf::int32 value);

  // required int32 len = 2;
  inline bool has_len() const;
  inline void clear_len();
  static const int kLenFieldNumber = 2;
  inline ::google::protobuf::int32 len() const;
  inline void set_len(::google::protobuf::int32 value);

  // required string value = 3;
  inline bool has_value() const;
  inline void clear_value();
  static const int kValueFieldNumber = 3;
  inline const ::std::string& value() const;
  inline void set_value(const ::std::string& value);
  inline void set_value(const char* value);
  inline void set_value(const char* value, size_t size);
  inline ::std::string* mutable_value();
  inline ::std::string* release_value();
  inline void set_allocated_value(::std::string* value);

  // @@protoc_insertion_point(class_scope:ServerInfo.Packet)
 private:
  inline void set_has_types();
  inline void clear_has_types();
  inline void set_has_len();
  inline void clear_has_len();
  inline void set_has_value();
  inline void clear_has_value();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 types_;
  ::google::protobuf::int32 len_;
  ::std::string* value_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_ServerInfo_2eproto();
  friend void protobuf_AssignDesc_ServerInfo_2eproto();
  friend void protobuf_ShutdownFile_ServerInfo_2eproto();

  void InitAsDefaultInstance();
  static Packet* default_instance_;
};
// ===================================================================


// ===================================================================

// Packet

// required int32 types = 1;
inline bool Packet::has_types() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Packet::set_has_types() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Packet::clear_has_types() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Packet::clear_types() {
  types_ = 0;
  clear_has_types();
}
inline ::google::protobuf::int32 Packet::types() const {
  return types_;
}
inline void Packet::set_types(::google::protobuf::int32 value) {
  set_has_types();
  types_ = value;
}

// required int32 len = 2;
inline bool Packet::has_len() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Packet::set_has_len() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Packet::clear_has_len() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Packet::clear_len() {
  len_ = 0;
  clear_has_len();
}
inline ::google::protobuf::int32 Packet::len() const {
  return len_;
}
inline void Packet::set_len(::google::protobuf::int32 value) {
  set_has_len();
  len_ = value;
}

// required string value = 3;
inline bool Packet::has_value() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Packet::set_has_value() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Packet::clear_has_value() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Packet::clear_value() {
  if (value_ != &::google::protobuf::internal::kEmptyString) {
    value_->clear();
  }
  clear_has_value();
}
inline const ::std::string& Packet::value() const {
  return *value_;
}
inline void Packet::set_value(const ::std::string& value) {
  set_has_value();
  if (value_ == &::google::protobuf::internal::kEmptyString) {
    value_ = new ::std::string;
  }
  value_->assign(value);
}
inline void Packet::set_value(const char* value) {
  set_has_value();
  if (value_ == &::google::protobuf::internal::kEmptyString) {
    value_ = new ::std::string;
  }
  value_->assign(value);
}
inline void Packet::set_value(const char* value, size_t size) {
  set_has_value();
  if (value_ == &::google::protobuf::internal::kEmptyString) {
    value_ = new ::std::string;
  }
  value_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Packet::mutable_value() {
  set_has_value();
  if (value_ == &::google::protobuf::internal::kEmptyString) {
    value_ = new ::std::string;
  }
  return value_;
}
inline ::std::string* Packet::release_value() {
  clear_has_value();
  if (value_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = value_;
    value_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void Packet::set_allocated_value(::std::string* value) {
  if (value_ != &::google::protobuf::internal::kEmptyString) {
    delete value_;
  }
  if (value) {
    set_has_value();
    value_ = value;
  } else {
    clear_has_value();
    value_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace ServerInfo

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ServerInfo_2eproto__INCLUDED
