// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ServerInfo.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "ServerInfo.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace ServerInfo {

namespace {

const ::google::protobuf::Descriptor* InfoPackage_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  InfoPackage_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_ServerInfo_2eproto() {
  protobuf_AddDesc_ServerInfo_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "ServerInfo.proto");
  GOOGLE_CHECK(file != NULL);
  InfoPackage_descriptor_ = file->message_type(0);
  static const int InfoPackage_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(InfoPackage, infotypes_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(InfoPackage, infolen_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(InfoPackage, infodata_),
  };
  InfoPackage_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      InfoPackage_descriptor_,
      InfoPackage::default_instance_,
      InfoPackage_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(InfoPackage, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(InfoPackage, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(InfoPackage));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_ServerInfo_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    InfoPackage_descriptor_, &InfoPackage::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_ServerInfo_2eproto() {
  delete InfoPackage::default_instance_;
  delete InfoPackage_reflection_;
}

void protobuf_AddDesc_ServerInfo_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\020ServerInfo.proto\022\nServerInfo\"C\n\013InfoPa"
    "ckage\022\021\n\tinfoTypes\030\001 \002(\005\022\017\n\007infoLen\030\002 \002("
    "\005\022\020\n\010infoData\030\003 \002(\tB\032\n\rcom.mypackageB\tMy"
    "Package", 127);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "ServerInfo.proto", &protobuf_RegisterTypes);
  InfoPackage::default_instance_ = new InfoPackage();
  InfoPackage::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_ServerInfo_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_ServerInfo_2eproto {
  StaticDescriptorInitializer_ServerInfo_2eproto() {
    protobuf_AddDesc_ServerInfo_2eproto();
  }
} static_descriptor_initializer_ServerInfo_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int InfoPackage::kInfoTypesFieldNumber;
const int InfoPackage::kInfoLenFieldNumber;
const int InfoPackage::kInfoDataFieldNumber;
#endif  // !_MSC_VER

InfoPackage::InfoPackage()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void InfoPackage::InitAsDefaultInstance() {
}

InfoPackage::InfoPackage(const InfoPackage& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void InfoPackage::SharedCtor() {
  _cached_size_ = 0;
  infotypes_ = 0;
  infolen_ = 0;
  infodata_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

InfoPackage::~InfoPackage() {
  SharedDtor();
}

void InfoPackage::SharedDtor() {
  if (infodata_ != &::google::protobuf::internal::kEmptyString) {
    delete infodata_;
  }
  if (this != default_instance_) {
  }
}

void InfoPackage::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* InfoPackage::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return InfoPackage_descriptor_;
}

const InfoPackage& InfoPackage::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_ServerInfo_2eproto();
  return *default_instance_;
}

InfoPackage* InfoPackage::default_instance_ = NULL;

InfoPackage* InfoPackage::New() const {
  return new InfoPackage;
}

void InfoPackage::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    infotypes_ = 0;
    infolen_ = 0;
    if (has_infodata()) {
      if (infodata_ != &::google::protobuf::internal::kEmptyString) {
        infodata_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool InfoPackage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 infoTypes = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &infotypes_)));
          set_has_infotypes();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_infoLen;
        break;
      }

      // required int32 infoLen = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_infoLen:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &infolen_)));
          set_has_infolen();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(26)) goto parse_infoData;
        break;
      }

      // required string infoData = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_infoData:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_infodata()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->infodata().data(), this->infodata().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void InfoPackage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required int32 infoTypes = 1;
  if (has_infotypes()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->infotypes(), output);
  }

  // required int32 infoLen = 2;
  if (has_infolen()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->infolen(), output);
  }

  // required string infoData = 3;
  if (has_infodata()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->infodata().data(), this->infodata().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      3, this->infodata(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* InfoPackage::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required int32 infoTypes = 1;
  if (has_infotypes()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->infotypes(), target);
  }

  // required int32 infoLen = 2;
  if (has_infolen()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->infolen(), target);
  }

  // required string infoData = 3;
  if (has_infodata()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->infodata().data(), this->infodata().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->infodata(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int InfoPackage::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int32 infoTypes = 1;
    if (has_infotypes()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->infotypes());
    }

    // required int32 infoLen = 2;
    if (has_infolen()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->infolen());
    }

    // required string infoData = 3;
    if (has_infodata()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->infodata());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void InfoPackage::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const InfoPackage* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const InfoPackage*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void InfoPackage::MergeFrom(const InfoPackage& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_infotypes()) {
      set_infotypes(from.infotypes());
    }
    if (from.has_infolen()) {
      set_infolen(from.infolen());
    }
    if (from.has_infodata()) {
      set_infodata(from.infodata());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void InfoPackage::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void InfoPackage::CopyFrom(const InfoPackage& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool InfoPackage::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000007) != 0x00000007) return false;

  return true;
}

void InfoPackage::Swap(InfoPackage* other) {
  if (other != this) {
    std::swap(infotypes_, other->infotypes_);
    std::swap(infolen_, other->infolen_);
    std::swap(infodata_, other->infodata_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata InfoPackage::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = InfoPackage_descriptor_;
  metadata.reflection = InfoPackage_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace ServerInfo

// @@protoc_insertion_point(global_scope)
